use_frameworks!

platform :ios, '8.0'

target 'BeautyMacroMoudle_Example' do
  pod 'BeautyMacroMoudle', :path => '../'

  target 'BeautyMacroMoudle_Tests' do
    inherit! :search_paths

    
  end
end
